services:
  liferay:
    image: liferay/portal:7.1.3-ga4
    container_name: test-liferay
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
    environment:
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_lass_UPPERCASEN_ame=org.postgresql.Driver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:postgresql://postgres:5432/lportal
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=liferay
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=passw0rd
  postgres:
    image: postgres:12
    container_name: test-postgres
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=liferay
      - POSTGRES_DB=lportal
    ports:
      - "5433:5432"

volumes:
  liferay:
