services:
  liferay:
    image: demo-liferay:1.1.0
    container_name: demo-liferay
    depends_on:
      lportal-db:
        condition: service_healthy
    ports:
      - "8787:8787"
      - "8080:8080"
  lportal-db:
    image: postgres:12
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "push"]
      interval: 5s
      retries: 5
      start_period: 10s
    container_name: test-postgres
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=liferay
      - POSTGRES_DB=lportal
    ports:
      - "5432:5432"

volumes:
  liferay:
