services:
  liferay:
    image: demo-liferay:1.1.0
    container_name: demo-liferay
    depends_on:
      lportal-db:
        condition: service_healthy
    ports:
      - "8787:8787"
      - "8080:8080"
  lportal-db:
    image: demo-db-liferay:1.0.0
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "liferay"]
      interval: 5s
      retries: 5
      start_period: 10s 
    container_name: demo-db-liferay
    ports:
      - "5433:5432"

volumes:
  liferay:
